### ISSUE TITLE
Refactor pobieranie danych, część 1

### ISSUE THREAD

**Issue by iksemot** [blstream/ShopMe_Frontend#121]
- Pobieranie danych powinno odbywać się w komponentach `screens` aby komponenty `components` były odpowiedzialne tylko za obsługę pobranych danych.
- Wyjątkiem prawdopodobnie będzie komponent `Layout` który będzie sam dla siebie pobierał dane. 
- Komponenty `components` umieszczone na komponentach `screens` powinny przyjmować potrzebne dane w props, odpowiednio reagować na ich zmianę, i wystawiać zmiany przez wywołania funkcji przekazanych w `props` (podobnie jak https://reactjs.org/docs/lifting-state-up.html)

**Comment by iksemot** [comment]
W najprostszej formie flow danych będzie mniej więcej taki:

```
Screen
    state = {result}
    fn getData(args)
        fetch(url/args).then(set state of result)
    fn render
        Form onSubmit={getData} result={state.result}

Form
    handleSubmit
        if (isInputValid)
            props.onSubmit(inputValue)
```

- Screen  trzyma w stanie wyniki zapytania `result`, ma zdefiniowaną metodę `getData` która pobiera dane i ustawia stan `result`.
- Do Form przekazywane są obie te rzeczy ^.
- Form w handleSubmie (funkcji wywołanej na klik) sprawdza sobie co tam potrzebuje i wywołuje z props `onSubmit` które tak naprawdę jest funkcją `Screen.getData`
- Czego nie ma w przykładzie to użycie `result` które `Form` dostaje w props. Ale dzięki temu może zareagować na otrzymanie wyników.


Troszkę bardziej rozbudowanym przykładem będzie:
```
Screen
    state = {result}
    fn getData(args)
        return fetch(url/args) then set state of result
    fn render
        Form onSubmit={getData} result={state.result}

Form
    handleSubmit
        if (isInputValid)
            props.onSubmit(inputValue).then(do some magic)
```

- Różnica, getData **zwraca** całego fetcha
- W ten sposób Form w `handleSubmit` wywołując `props.onSubmit` może dopisać kolejnego `then` i poczekać aż zapytanie się wykona

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/135

pierwsza część zadania

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/137

część druga

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/138

To chyba wszystkie fetche jakie mamy do tej pory
