### ISSUE TITLE
Usunięcie refów i getWrappedInstance

### ISSUE THREAD

**Issue by iksemot** [blstream/ShopMe_Frontend#133]
By pozbyć się referencji do składowych komponentów formularza, należy przekazywać wartości z rodzica do dzieci tak by one same na 'znak' przekazywały swój stan. W założeniu, na poziomie rodzica powinna być flaga mówiąca dzieciom że powinny się zwalidować, domyślnie ustawiona na 'undefined'.
```
state: {
    doValidate: undefined
```
Na zatwierdzenie formularza, rodzic zmienia stan tej flagi na 'true'. W rezultacie przekazana wcześniej metoda będzie wywoływana z poziomu dziecka,
```
<TitleInput
    name="offerTitle"
    doValidate={this.state.doValidate}
    onValidate={this.setIsValid}
/>
```
skąd przekazany będzie rezultat walidacji do rodzica i zapisany w jego stanie ``` this.setState({ offerTitleIsValid: validationResult })```

Na bierząco powinien być sprawdzany aktualny stan walidacji wszystkich składowych formularza, by sprawdzić czy wszystkie z oczekiwanych pól są pozytywnie zwalidowane. Gdy dojdzie do sukcesu, czyli wszystkie flagi zwalidowanych dzieci w stanie rodzica będą pozytywne, można wtedy zebrać dane i wysłać dane do backendu.

By mieć pewność należy za każdym razem czyścić stan poprzedniej walidacji, natomiast wartości komponentów powinny cały czas odzwierciedlać swój aktualny stan.

Proponuje nie trzymać wszystkiego na płasko w stanie, głównie po ty by łatwiej filtrować stan walidacji
```
this.state = {
      doValidate: undefined,
      validationResult: {
        ...
      componentsValues: {
        ...
```
W razie jakichkolwiek pytań, służę pomocą :)

**Comment by mmszymczak** [comment]
@FrontlineZS Jeszcze pozostał formularz danych do faktury (InvoiceInputGroup.jsx)

**Comment by iksemot** [comment]
I `RegisterForm.jsx`

**Comment by mmszymczak** [comment]
Właściwie temat zamknięty, jednak ostała się jeszcze ostatnia referencja do komponentu AboutMeTextarea w formularzu rejestracji ;)

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/266
