### ISSUE TITLE
Wyniesienie layout poziom wyżej

### ISSUE THREAD

**Issue by iksemot** [blstream/ShopMe_Frontend#157]
Komponenty Screens nie powinny zawierać elementu `<Layout>`.

Proponuję modyfikację Routes.jsx i przekazywać do Route parametr render zamiast component: 
`<Route exact path="/" render={wrapInLayout(ScreensSearch)} />`

Implementacja wrapInLayout może wyglądać tak:
```
function wrapInLayout(Screen) {
  return () => <Layout><Screen /></Layout>;
}
```

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/158
