### ISSUE TITLE
Aktualizacja manifest.json i index.html

### ISSUE THREAD

**Issue by iksemot** [blstream/ShopMe_Frontend#22]
W plikach `public/manifest.json` oraz `public/index.html` znajdują się złe tytuły i opisy.

Dobrze byłoby zaktualizować te pliki aby wskazywały, że aplikacją jest ShopMe, a nie React App.

Czym jest manifest: https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by pszmurlo** [comment]
PR do tego zadania znajduje się tu:
[https://github.com/blstream/ShopMe_Frontend/pull/48]
Jeśli PR zostanie zaakceptowany można zamknąć.
