### ISSUE TITLE
Weryfikacja serwera mockowego

### ISSUE THREAD

**Issue by mmszymczak** [blstream/ShopMe_Frontend#228]
Od dłuższego czasu wszyscy korzystają z serwera produkcyjnego nawet do pracy lokalnej, więc możliwe że serwer mockowy nie działa lub nie jest zbyt aktualny. 

Zakładam że projekt będzie leżał w repozytorium pewnie dłuższy czas, ale nie wykluczone że jego wersja produkcyjna może upaść prędzej. Więc żeby projekt był dostępny dla każdego kto by chciał uruchomić sobie lokalnie by sprawdzić jego zawartośc, to w najlepszym przypadku powinien byc działający serwer mockowy.

Nalezy zweryfikować czy serwer mockowy działa prawidłowo, jeżeli jest to do ogarnięcia to pozostałbym przy tym rozwiązaniu. Jeżeli jest to większy nakład pracy który mija się z celem to można się go pozbyć całkowicie z projektu :)

**Comment by Ardneh3** [comment]
Jeśli nikt się nie zgłasza to ja mogę to wziąć tylko potrzebowałbym parę wskazówek, bo pierwszy raz coś takiego bym robił :)
