### ISSUE TITLE
Scroll to the top of the page

### ISSUE THREAD

**Issue by mmszymczak** [blstream/ShopMe_Frontend#229]
Aktualnie gdy przechodzi się między podstronami, zdaża się że zostajemy w jej dolnej części. 

Przykład: Na głównej stronie klikam w stopce odnośnik 'Inne', przekierowuje mnie na strone wyników i widze tylko koniec tabelki i całą stopke.

Fajnie byłoby gdyby po zmianie url'a nastąpiło przesunięcie widoku na samą góre strony.

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/232
