### ISSUE TITLE
Ulepszenie obsługi błędów

### ISSUE THREAD

**Issue by iksemot** [blstream/ShopMe_Frontend#233]
Zadanie ma na celu poprawę obsługę odpowiedzi z grupy sukcesów oraz wprowadzenie mechanizmu obsługi nie fatalnych błędów (non-fatal errors).

**Obsługa odpowiedzi z grupy 2xx**
Obecnie metody helpera http: get i post, przyjmują że jedynym poprawnym kodem odpowiedzi serwera jest kod 200 OK. Jest to błąd i cała grupa powinna być obsłużona w ten sam sposób. Proponuję po użycie atrybutu `response.ok` (https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) zamiast ręcznego sprawdzania kodu odpowiedzi.

**Poprawa zachowania pobierania danych**
W screenach gdzie pobierane są dane, w funkcjach `then` należy zweryfikować czy dostajemy w ogóle odpowiedź. Wydaje mi się, że obecnie w przypadku błędnych odpowiedzi z serwera następuje niepoprawne zachowanie wykonania się tego kodu.

**Obsługa błędów nie fatalnych**
Błędy serwera możemy podzielić na 2 grupy: fatalne i nie-fatalne. Błędy fatalne to błędy grupy 5xx które raczej wskazują na błędną implementację serwera lub błąd w samym serwerze aplikacji. Błędny nie-fatalne to błędy grupy 4xx które są zwracane świadomie przez serwer i mają raczej związek z błędnymi danymi.

Błędy fatalne powinny być obsłużone jak dotychczas - błędem na cały obszar `<main>`

Błędy nie-fatalne są błędami o których chcemy poinformować użytkownika bo być może wprowadził niepoprawne dane i zapytanie może być powtórzone, więc komunikat błędu nie powinien być wyświetlany na cały obszar `<main>` ale wewnątrz niego (póki co proponujemy czerwony prostokąt gdzieś pod headerem)

Aby rozróżnić błędy fatalne od nie-fatalnych można sprawdzić czy odpowiedź zawiera pole `message` które jest zwracane przez nasz serwer (do zweryfikowania z backendowcami), treść z tego pola powinna być wyświetlona jako komunikat błędu.

**Ulepszenie osbługi błędów nie fatalnych**
Komunikat zwracane przez serwer nie są zbyt "user friendly" więc mechanizm może być ulepszony poprzez wprowadzenie tłumaczeń po naszej stronie, jeśli takie tłumaczenie istnieje powinno być użyte, jeśli go nie ma wtedy użyty byłby komunikat zwrócony przez serwer.

Struktura tłumaczeń błędów może wyglądać tak:

```
"endpointError": {
	"offers": {
		"post": {
			"400": "Niepoprawnie wypełnione pola",
			"401": "Brak uprawnień do dodania nowej oferty"
		}
	}
}
```

**Comment by mmszymczak** [comment]
https://tracker.intive.com/jira/browse/PRODPFIP-375
