### ISSUE TITLE
CSS: Wprowadzenie prawidłowych wartości rem

### ISSUE THREAD

**Issue by mmszymczak** [blstream/ShopMe_Frontend#87]
Aktualnie w projekcie poplątane są remy i pixele, zadanie polega na odpowiednim zdefiniowaniu rozmiaru czcionki oraz kontenerów dla całego projektu, tak by wartość np. 22px odpowiadała 2.2rem.

Wstępne ustalenia używania rem tyczą się tylko kontenerów i czcionek, co oznacza w obrębie tego zadania również zamiane istniejących wartości px na rem.

Tutaj fajny artykuł w którym sa zawarte wszystkie informacje niezbędne do zrozumienia i prawidłowej implementacji:
https://www.sitepoint.com/understanding-and-using-rem-units-in-css/

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/119
