### ISSUE TITLE
Dodanie fontów do lokalnych zasobów

### ISSUE THREAD

**Issue by mmszymczak** [blstream/ShopMe_Frontend#90]
Chcemy być niezależni od zewnętrznych dostawców i zawsze mieć fonty dostępne w projekcie, wymaga to pobrania odpowiednich(wybranych przez zespół) fontów i dodanie ich do lokalnych zasobów projektu. Następnie wykorzystać je na przestrzeni całej aplikacji.

**Comment by Ardneh3** [comment]
https://github.com/blstream/ShopMe_Frontend/pull/114
