### ISSUE TITLE
Poprawne ładowanie globalnych styli

### ISSUE THREAD

**Issue by mmszymczak** [blstream/ShopMe_Frontend#91]
Aktualnie index.css ma zdefiniowane style niezbędne dla całego projektu i jest dołączany do index.html. Działa to dobrze gdy zaczynamy zwiedzanie aplikacji od strony głównej, natomiast gdy wyślemy komuś link do konkretnej usługi, ten któs zobaczy że strona się rozjeżdża. 

Należy zorientować się jak dodać index.css do aplikacji by niezależnie którą podstrone przeładujemy/odświeżymy, nie straci ona na walorach wizualnych (będzie wyglądała tak samo ;)

**Comment by Ardneh3** [comment]
Może dodać diva do index.html i komponent, który będzie się renderować w tym divie i zaimportować w nim style globalne? Wydaje mi się, że powinno być to wtedy wczytywane niezależnie od odświeżenia, ale mogę się mylić
